[project]
name = "neuronowy-model-predykcyjny"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.30.0",
  "scikit-learn==1.5.0",
  "joblib==1.4.2",
  "numpy==1.26.4",
  "jinja2"
]

[tool.uv]
